<?php
#Activities
T_("Merci de choisir une activité");
T_("Alimentation et gastronomie");
T_("Animaux");
T_("Articles pour bébé");
T_("Arts et culture");
T_("Auto et moto");
T_("Bijouterie");
T_("Chaussures et accessoires");
T_("Fleurs, cadeaux et artisanat");
T_("Hifi, photo et vidéo");
T_("Informatique et logiciels");
T_("Lingerie et Adulte");
T_("Maison et jardin");
T_("Mode et accessoires");
T_("Santé et beauté");
T_("Services");
T_("Sports et loisirs");
T_("Téléchargement");
T_("Téléphonie et communication");
T_("Voyage et tourisme");
T_("Électroménager");
T_("Autre activité ...");

#Pays
T_("Sélectionnez un pays");
T_("Allemagne");
T_("Autriche");
T_("Belgique");
T_("Canada");
T_("Chine");
T_("Espagne");
T_("Finlande");
T_("France");
T_("Grèce");
T_("Italie");
T_("Japon");
T_("Luxembourg");
T_("Pays-bas");
T_("Pologne");
T_("Portugal");
T_("République Tchèque");
T_("Royaume-Uni");
T_("Suède");
T_("Suisse");
T_("Danemark");
T_("États-Unis");
T_("Hong-Kong");
T_("Norvège");
T_("Australie");
T_("Singapour");
T_("Irlande");
T_("Nouvelle-Zélande");
T_("Corée du Sud");
T_("Israël");
T_("Afrique du Sud");
T_("Nigeria");
T_("Côte d'Ivoire");
T_("Togo");
T_("Bolivie");
T_("Ile Maurice");
T_("Roumanie");
T_("Slovaquie");
T_("Algérie");
T_("Samoa Américaines");
T_("Andorre");
T_("Angola");
T_("Anguilla");
T_("Antigua et Barbuda");
T_("Argentine");
T_("Arménie");
T_("Aruba");
T_("Azerbaïdjan");
T_("Bahamas");
T_("Bahreïn");
T_("Bangladesh");
T_("Barbade");
T_("Bélarus");
T_("Belize");
T_("Bénin");
T_("Bermudes");
T_("Bhoutan");
T_("Botswana");
T_("Brésil");
T_("Brunéi Darussalam");
T_("Burkina Faso");
T_("Burma (Myanmar)");
T_("Burundi");
T_("Cambodge");
T_("Cameroun");
T_("Cap-Vert");
T_("Centrafricaine, République");
T_("Tchad");
T_("Chili");
T_("Colombie");
T_("Comores");
T_("Congo, Rép. Dém.");
T_("Congo, Rép.");
T_("Costa Rica");
T_("Croatie");
T_("Cuba");
T_("Chypre");
T_("Djibouti");
T_("Dominica");
T_("République Dominicaine");
T_("Timor oriental");
T_("Équateur");
T_("Égypte");
T_("El Salvador");
T_("Guinée Équatoriale");
T_("Érythrée");
T_("Estonie");
T_("Éthiopie");
T_("Falkland, Îles");
T_("Féroé, Îles");
T_("Fidji");
T_("Gabon");
T_("Gambie");
T_("Géorgie");
T_("Ghana");
T_("Grenade");
T_("Groenland");
T_("Gibraltar");
T_("Guadeloupe");
T_("Guam");
T_("Guatemala");
T_("Guernesey");
T_("Guinée");
T_("Guinée-Bissau");
T_("Guyana");
T_("Haîti");
T_("Heard, Île et Mcdonald, Îles");
T_("Saint-Siege (État de la Cité du Vatican)");
T_("Honduras");
T_("Islande");
T_("Inde");
T_("Indonésie");
T_("Iran");
T_("Iraq");
T_("Man, Île de");
T_("Jamaique");
T_("Jersey");
T_("Jordanie");
T_("Kazakhstan");
T_("Kenya");
T_("Kiribati");
T_("Corée, Rép. Populaire Dém. de");
T_("Koweït");
T_("Kirghizistan");
T_("Laos");
T_("Lettonie");
T_("Liban");
T_("Lesotho");
T_("Libéria");
T_("Libyenne, Jamahiriya Arabe");
T_("Liechtenstein");
T_("Lituanie");
T_("Macao");
T_("Macédoine");
T_("Madagascar");
T_("Malawi");
T_("Malaisie");
T_("Maldives");
T_("Mali");
T_("Malte");
T_("Marshall, Îles");
T_("Martinique");
T_("Mauritanie");
T_("Hongrie");
T_("Mayotte");
T_("Mexique");
T_("Micronésie");
T_("Moldova");
T_("Monaco");
T_("Mongolie");
T_("Monténégro");
T_("Montserrat");
T_("Maroc");
T_("Mozambique");
T_("Namibie");
T_("Nauru");
T_("Népal");
T_("Antilles Néerlandaises");
T_("Nouvelle-Calédonie");
T_("Nicaragua");
T_("Niger");
T_("Niué");
T_("Norfolk, Île");
T_("Mariannes du Nord, Îles");
T_("Oman");
T_("Pakistan");
T_("Palaos");
T_("Palestinien Occupé, Territoire");
T_("Panama");
T_("Papouasie-Nouvelle-Guinée");
T_("Paraguay");
T_("Pérou");
T_("Philippines");
T_("Pitcairn");
T_("Porto Rico");
T_("Qatar");
T_("Réunion, Île de la");
T_("Russie, Fédération de");
T_("Rwanda");
T_("Saint-Barthélemy");
T_("Saint-Kitts-et-Nevis");
T_("Sainte-Lucie");
T_("Saint-Martin");
T_("Saint-Pierre-et-Miquelon");
T_("Saint-Vincent-et-Les Grenadines");
T_("Samoa");
T_("Saint-Marin");
T_("Sao Tomé-et-Principe");
T_("Arabie Saoudite");
T_("Sénégal");
T_("Serbie");
T_("Seychelles");
T_("Sierra Leone");
T_("Slovénie");
T_("Salomon, Îles");
T_("Somalie");
T_("Géorgie du Sud et les Îles Sandwich du Sud");
T_("Sri Lanka");
T_("Soudan");
T_("Suriname");
T_("Svalbard et Île Jan Mayen");
T_("Swaziland");
T_("Syrienne");
T_("Taïwan");
T_("Tadjikistan");
T_("Tanzanie");
T_("Thaïlande");
T_("Tokelau");
T_("Tonga");
T_("Trinité-et-Tobago");
T_("Tunisie");
T_("Turquie");
T_("Turkménistan");
T_("Turks et Caiques, Îles");
T_("Tuvalu");
T_("Ouganda");
T_("Ukraine");
T_("Émirats Arabes Unis");
T_("Uruguay");
T_("Ouzbékistan");
T_("Vanuatu");
T_("Venezuela");
T_("Vietnam");
T_("Îles Vierges Britanniques");
T_("Îles Vierges des États-Unis");
T_("Wallis et Futuna");
T_("Sahara Occidental");
T_("Yémen");
T_("Zambie");
T_("Zimbabwe");
T_("Albanie");
T_("Afghanistan");
T_("Antarctique");
T_("Bosnie-Herzégovine");
T_("Bouvet, Île");
T_("Océan Indien, Territoire Britannique de L");
T_("Bulgarie");
T_("Caïmans, Îles");
T_("Christmas, Île");
T_("Cocos (Keeling), Îles");
T_("Cook, Îles");
T_("Guyane Française");
T_("Polynésie Française");
T_("Terres Australes Françaises");
T_("Åland, Îles");